const API_BASE = 'http://localhost:8000/api';
const HEADERS = {
  'Content-Type': 'application/json',
};

// 顯示 QR Code
async function setup2FA(username) {
  try {
    const response = await fetch(`${API_BASE}/generate-2fa-secret`, {
      method: 'POST',
      headers: HEADERS,
      body: JSON.stringify({ username }),
    });

    if (!response.ok) {
      throw new Error('Failed to set up 2FA');
    }

    const { qrCode } = await response.json();

    // 顯示 QR Code
    const qrCodeImage = document.createElement('img');
    qrCodeImage.src = qrCode;
    document.body.appendChild(qrCodeImage);

    console.log('2FA setup complete. Scan the QR Code with your authenticator app.');
  } catch (error) {
    console.error('Error setting up 2FA:', error);
  }
}

// 提交 OTP
async function verifyOTP(username, otp) {
  try {
    const response = await fetch(`${API_BASE}/verify-otp`, {
      method: 'POST',
      headers: HEADERS,
      body: JSON.stringify({ username, otp }),
    });

    if (!response.ok) {
      throw new Error('Failed to verify OTP');
    }

    const data = await response.json();
    console.log('OTP verified successfully:', data.message);
  } catch (error) {
    console.error('Error verifying OTP:', error);
  }
}

// 測試流程
(async function test2FA() {
  const username = 'testuser';

  // Step 1: 設置 2FA
  console.log('Setting up 2FA...');
  await setup2FA(username);

  // Step 2: 用戶掃描 QR Code 並生成 OTP
  console.log('Please use your authenticator app to generate an OTP.');

  // 模擬用戶輸入 OTP
  const otp = prompt('Enter the OTP generated by your authenticator app:');

  // Step 3: 驗證 OTP
  console.log('Verifying OTP...');
  await verifyOTP(username, otp);
})();